# 公共配置文件

spring:
  application:
    name: ai-backend
  # 默认 dev 环境
#  profiles:
#    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mbti
    username: xzz
    password: Mdjfb123!
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
#    password: 906684
#  shardingsphere:
#    #数据源配置
#    datasource:
#      # 多数据源以逗号隔开即可
#      names: mbti
#      mbti:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        jdbc-url: jdbc:mysql://localhost:3306/mbti?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true&characterEncoding=utf8
#        username: root
#        password: 12345678
#    # 规则配置
#    rules:
#      sharding:
#        # 分片算法配置
#        sharding-algorithms:
#          # 自定义分片规则名
#          answer-table-inline:
#            ## inline 类型是简单的配置文件里面就能写的类型，其他还有自定义类等等
#            type: INLINE
#            props:
#              algorithm-expression: user_answer_$->{appId % 2}
#        tables:
#          user_answer:
#            actual-data-nodes: mbti.user_answer_$->{0..1}
#            # 分表策略
#            table-strategy:
#              standard:
#                sharding-column: appId
#                sharding-algorithm-name: answer-table-inline

  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 86400
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.xz.aiTest.controller

# 小细节 这里值映射是有数据类型的 带上“”才是字符串 其他是整型
ai:
 key: "49510645eaa841b28781213f6b1110c5.8fbot56G3IWd4ypr"
